Repository satRdays/hugo-satrdays-theme, pull requests merged in 2020-10, with the labels that each got.

#36 update develop, which I should have been mainting but didn't
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  layouts/partials/schedule.html
  layouts/partials/tweetthis.html
  static/css/satrday.css
Labels: bug

#37 Include all the missing assets from hugo-agency-theme
  archetypes/default.md
  layouts/404.html
  layouts/partials/about.html
  layouts/partials/head.html
  layouts/partials/js.html
  layouts/partials/nav.html
  layouts/partials/services.html
  static/css/bootstrap-v3.3.7/bootstrap.css
  static/css/bootstrap-v3.3.7/bootstrap.min.css
  static/css/jquery.form-validator-v2.3.44/theme-default.css
  static/css/jquery.form-validator-v2.3.44/theme-default.min.css
  static/font-awesome-v4.7.0/css/font-awesome.css
  static/font-awesome-v4.7.0/css/font-awesome.min.css
  static/font-awesome-v4.7.0/fonts/FontAwesome.otf
  static/font-awesome-v4.7.0/fonts/fontawesome-webfont.eot
  static/font-awesome-v4.7.0/fonts/fontawesome-webfont.svg
  static/font-awesome-v4.7.0/fonts/fontawesome-webfont.ttf
  static/font-awesome-v4.7.0/fonts/fontawesome-webfont.woff
  static/font-awesome-v4.7.0/fonts/fontawesome-webfont.woff2
  static/fonts/bootstrap-v3.3.7/glyphicons-halflings-regular.eot
  static/fonts/bootstrap-v3.3.7/glyphicons-halflings-regular.svg
  static/fonts/bootstrap-v3.3.7/glyphicons-halflings-regular.ttf
  static/fonts/bootstrap-v3.3.7/glyphicons-halflings-regular.woff
  static/fonts/bootstrap-v3.3.7/glyphicons-halflings-regular.woff2
  static/img/404/404.jpg
  static/img/about/1.jpg
  static/img/about/2.jpg
  static/img/about/3.jpg
  static/img/about/4.jpg
  static/img/logos/aetuts.jpg
  static/img/logos/creative-market.jpg
  static/img/logos/designmodo.jpg
  static/img/logos/envato.jpg
  static/img/logos/microlancer.jpg
  static/img/logos/themeforest.jpg
  static/img/logos/wordpress.jpg
Labels: enhancement, hacktoberfest-accepted

#32 nav-bar transition / Empty menu items
  static/css/satrday.css
Labels: enhancement, hacktoberfest-accepted

#39 Merge speaker talk data file
  data/schedule/Talk01.toml
  data/schedule/Talk02.toml
  layouts/index.html
  layouts/partials/hackathon.html
  layouts/partials/modals.html
  layouts/partials/portfolio.html
  layouts/partials/schedule.html
  layouts/partials/team.html
  layouts/partials/tweetthis.html
Labels: hacktoberfest-accepted
